### ISSUE TITLE
[BUG] Uncaught Error: Call to undefined function exif_imagetype()

### ISSUE THREAD

**Issue by MeanZhang** [linuxserver/docker-freshrss#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I requested `/api/fever.php?api=&favicons=`, but got 500 error.
```
curl --http2 -X POST -H "Host:**********" -H "content-type:application/x-www-form-urlencoded" -H "content-length:40" -H "accept-encoding:gzip" -d "api_key=00d26afa46323ab158b6ea566ffe3d1f" "https://**********/api/fever.php?api=&favicons="
```

### Expected Behavior

Something like this:
```
{
  "api_version": 3,
  "auth": 1,
  "last_refreshed_on_time": 1705215407,
  "favicons": [
    {
      "id": 1,
      "data": "image/vnd.microsoft.icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AAAAAACeWU4JmE1BHbaBeVGye3K9qWpg8aFdUv2gXFH9qGlf8bJ7cry3g3tQmE1CHZ5ZTgnbwr4A////AP///wCeWU4Jm1JHI692bIinaV7WtoJ67OHMxP/ex7//y6md/8ijl/+3gnrsp2hd1q91bIibUkcjnllOCf///wD///8AmE1BHa92bYioal/i4czE////////////7+Db/9W4rv/VuK7/7+Db/+HMxP+nZ13ir3VsiJhNQR3///8A////ALaCeVGoaV/W4czE////////////+/Tx/9W4rv/VuK7/1biu/9W4rv///fz/4czE/6doXda2gXlR////AP///wCzfHO9uYeA7P////////////////v08f/VuK7/1biu/9W4rv/l0cn///////////+1gHfssnpxvf///wD///8AqWth8eHMxP/////////////////hzMT/4czE/+HMxP/16ub////////////37+v/4czE/6hpX/H///8A////AKFeU/316ub///////v08f/bwrn/9+/r///////////////////////ex77/2L2z/+/g2/+gXFH9////AP///wChXlP97+Db///////bwrn/69vV//v08f//////////////////////3se+/9W4rv/v4Nv/oFxS/f///wD///8Aqmxi8eHMxP/79PH/1biu/9W4rv/VuK7/+/Tx//////////////38/+vb1f/VuK7/4czE/6lqYPH///8A////ALN8c725h3/s//38/9W4rv/VuK7/1biu/9W4rv/79PH///////v08f/VuK7/59bQ/7iEfOyye3K9////AP///wC2gnlSqGpf1uHMxP/VuK7/1biu/9i9s//YvbP/8eXg/////////fz/3se+/97Hv/+naV7WtoJ5Uv///wD///8AmE1BHbB2bYirbWPiwpmN/9W4rv/bwrn/9+/r//Hl4P//////9erm/9vCuf+oaV/ir3VsiJhNQR3///8A////AJ5ZTgmbUkcjsHdtiKlrYda8jIXszq6j/8upnf/OrqP/4czE/7mHf+yoaV/Wr3ZtiJtSRyOeWU4J////AP///wAAAAAAnllOCZhNQR22gnpSs310vaptY/GiX1T9ol9U/apsYvGzfHO9toJ5UphNQR2eWU4J28K+AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A//8AAPgfAADgBwAAwAMAAMADAACAAQAAgAEAAIABAACAAQAAgAEAAIABAADAAwAAwAMAAOAHAAD4HwAA//8AAA=="
    },
    {
      "id": 2,
      "data": "image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAAAN0AAADdAXBTogcAAACKUExURUxpcSIiIiIiIh4eHiQkJCIiIiIiIiIiIvf39/T09EZGRrW1ta+vryYmJiIiIiEhISEhISAgIHZ2dtzc3LOzsyQkJO7u7r+/vyIiIiIiIiIiIiMjIyEhISQkJCIiIiIiIiEhISMjI319ff39/TU1NcHBwfj4+P///97e3ufn5y8vL56eniIiIv///yHXm7AAAAAsdFJOUwB45Asg+H982dLcwLwDy4ZZL8XAvfHMvcFiS6k9Fdlyt5rD5ufH3vHGxu6/ARtwjAAAAORJREFUOMulk9kSgjAMRRWoVZStiAiKG4hb8v+/Z0ecSmvojON9Sueeh6S5GY1+lOdZbZczFrnDfuyAlFMEtJ2s4a1wS9jVEXramK0E+ww0Ga2UO/iSE39GOwCpMHkD4+59Sv2u8K+iKyY6MMW6eRULnA0AuGIkwBWAuQZwE2gRhRU4L/HiWwG44TSD5SCQw73F1ALM5R9c8GEF4CSHtQKQy2kNYKIBbKWAMQlAUw8AQi0rFTqQhPS6D56RVl27Ust7xHQ725vR9jZ9/1gRud6qVtYJfRhB4Rhp/T69iDHu/nO8hJ7YKFFM9bn+HwAAAFd6VFh0UmF3IHByb2ZpbGUgdHlwZSBpcHRjAAB4nOPyDAhxVigoyk/LzEnlUgADIwsuYwsTIxNLkxQDEyBEgDTDZAMjs1Qgy9jUyMTMxBzEB8uASKBKLgDqFxF08kI1lQAAAABJRU5ErkJggg=="
    }
  ]
}
```
This is the [official docker](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker)'s response.

### Steps To Reproduce

```
curl --http2 -X POST -H "Host:**********" -H "content-type:application/x-www-form-urlencoded" -H "content-length:40" -H "accept-encoding:gzip" -d "api_key=****************" "https://**********/api/fever.php?api=&favicons="
```

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS aarch64
- How docker service was installed: https://docs.docker.com/engine/install/ubuntu/
```

### CPU architecture

arm64

### Docker creation

```
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/config
    ports:
      - 8082:80
    restart: unless-stopped
```

### Container logs

nginx error.log:
```
2024/01/14 15:11:59 [error] 291#291: *353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function exif_imagetype() in /app/www/p/api/fever.php:367
Stack trace:
#0 /app/www/p/api/fever.php(206): FeverAPI->getFavicons()
#1 /app/www/p/api/fever.php(575): FeverAPI->process()
#2 {main}
  thrown in /app/www/p/api/fever.php on line 367" while reading response header from upstream, client: 172.23.0.1, server: _, request: "POST /api/fever.php?api=&favicons= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "**********"
```

**Comment by homerr** [comment]
Confirmed this is an issue, trying to work out what's causing it. Will reference the FreshRSS container to see if there are any prereq's that have gone under the radar.

**Comment by homerr** [comment]
Located the missing module, added and resolved.
